// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

//Max Test
//Aidan test
//CAMI VENTED IN ELECTRICAL

//Matilda Test

//Lorcan Test

//Julia test

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import th8s class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    public static int shooterTalon1Port = 11;
    public static int shooterTalon2Port = 1;
    public static int intakeSpinTalon = 9;
    public static int intakeElevTalon = 8;
    public static int drivetrainFrontLeftTalonPort = 6;
    public static int drivetrainRearLeftTalonPort = 5;
    public static int drivetrainFrontRightTalonPort = 10;
    public static int drivetrainRearRightTalonPort = 7;
    public static int climbingTalonPort = 12;
    public static int beltsTalonPort = 4;
    public static int joystickPort = 0;
    public static int controllerPort = 0;

    //high port
      //public static double shooterPower = 0.83;
    //low port
    public static double shooterPower = 0.75;
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
}

